/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    SearchBar: typeof import('./src/components/user/SearchBar.vue')['default']
    UserCard: typeof import('./src/components/user/UserCard.vue')['default']
    UserList: typeof import('./src/components/user/UserList.vue')['default']
    UserModal: typeof import('./src/components/user/UserModal.vue')['default']
  }
}
